### ISSUE TITLE
Auto Reloading

### ISSUE THREAD

**Issue by karneaud** [weavejester/lein-ring#175]
does `auto-reload, auto-refresh and wrap-reload` apply to _.clj and .cljs_ files or **ANY** file within the source/ resource directory?

**Comment by MichaelBlume** [comment]
I suspect they only apply to Clojure source files. @weavejester can you confirm?

**Comment by weavejester** [comment]
`auto-reload` reloads Clojure source files. It's a server-side reload with dependencies, so the files need to be Clojure and need to have a `ns` declaration.

`auto-refresh` refreshes after any source or resource file is changed.

`wrap-reload` is just the middleware that the `auto-reload` function uses. Similarly, `auto-refresh` uses `wrap-refresh`.

My understanding is that your problem was solved, @karneaud?
